Use forked version of svg2ttf
freshdesk/webfonts-generator pull request #1
Opened 2020-05-03 09:33 UTC by Malolan-Balaji

This fixes icon misalignment in windows of Freshcaller. This will not break existing repos which use this package.

2020-05-04 06:40 UTC, rajasegar-c requested changes

2020-05-04 06:40 UTC, rajasegar-c commented on package.json
> +    "svg2ttf": "https://github.com/uchihamalolan/svg2ttf.git",
We need to move `svg2ttf` also under freshdesk, it is not recommended to link personal repos.

2020-05-07 04:03 UTC, rajasegar approved these changes

2020-05-07 04:06 UTC, rajasegar-c approved these changes

2020-05-07 05:24 UTC, merged